image_width: 448
image_height: 448
camera_matrix:
    rows: 3
    cols: 3
    data: [1600., 0., 112.,
           0., 1600., 112.,
           0., 0., 1.]
distortion_coefficients:
    rows: 1
    cols: 5
    data: [0., 0., 0., 0., 0.]
