name: gaze
device: auto
model:
  name: resnet
dataset:
  dir: /homes/lventurelli/Resources/GazeEstimator/dataset
  # dir: C:\uni\cv\GazeDetectionProject\GazeEstimator\dataset
  name: dataset.h5
  face_size: 224
output:
  dir: /homes/lventurelli/Resources/GazeEstimator/outputs
  # dir: C:\uni\cv\GazeDetectionProject\GazeEstimator\outputs
train:
  batch_size: 32
  # can be: L1, L2, SmoothL1
  loss: L2
  weight_decay: 0.0001
  # can be: sgd, adam, amsgrad
  optimizer: sgd
  base_lr: 0.01
  momentum: 0.9
  nesterov: True
  betas: 0.1
  # the subject used for testing
  test_id: 0
  validation_ratio: 0.1
  log_period: 20
  checkpoint_period: 1
scheduler:
  epochs: 3
  # can be: multistep, cosine
  type: multistep
  milestones: [ 8, 9 ]
  lr_decay: 0.1
  lr_min_factor: 0.001